import { Service } from "../models/service.model";
import { Provider } from "../models/provider.model";
import { User } from "../models/user.model";
import { hashPassword } from "../utils/hash";

const SEED_PROVIDER_PASSWORD = "Provider123!";

function slugifyEmail(fullName: string): string {
  return (
    fullName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, ".")
      .replace(/^\.|\.$/g, "") + "@karya.demo"
  );
}

const SERVICES = [
  {
    name: "Deep Home Cleaning",
    slug: "deep-home-cleaning",
    category: "cleaning",
    icon: "Sparkles",
    description: "Full-home deep clean covering kitchens, bathrooms, floors and surfaces.",
    basePrice: 1200,
    priceUnit: "session" as const,
  },
  {
    name: "Bathroom Sanitization",
    slug: "bathroom-sanitization",
    category: "cleaning",
    icon: "Droplet",
    description: "Deep sanitization and descaling for bathrooms.",
    basePrice: 1500,
    priceUnit: "session" as const,
  },
  {
    name: "Laundry & Ironing",
    slug: "laundry-ironing",
    category: "laundry",
    icon: "Shirt",
    description: "Wash, dry and iron pickup service.",
    basePrice: 200,
    priceUnit: "session" as const,
  },
  {
    name: "Electrical Repair & Wiring",
    slug: "electrical-repair",
    category: "electrical",
    icon: "Zap",
    description: "Fan, switchboard, and wiring repairs from certified electricians.",
    basePrice: 450,
    priceUnit: "session" as const,
  },
  {
    name: "General Repairs",
    slug: "general-repairs",
    category: "repairs",
    icon: "Wrench",
    description: "Household fixes — from squeaky doors to loose fittings.",
    basePrice: 500,
    priceUnit: "session" as const,
  },
  {
    name: "Furniture Assembly & Carpentry",
    slug: "furniture-carpentry",
    category: "carpentry",
    icon: "Hammer",
    description: "Assembly, repairs and custom woodwork.",
    basePrice: 500,
    priceUnit: "session" as const,
  },
  {
    name: "Lawn & Garden Care",
    slug: "lawn-garden-care",
    category: "gardening",
    icon: "Leaf",
    description: "Mowing, trimming and garden upkeep.",
    basePrice: 800,
    priceUnit: "session" as const,
  },
  {
    name: "Wall Painting",
    slug: "wall-painting",
    category: "painting",
    icon: "PaintRoller",
    description: "Interior and exterior wall painting, priced per square foot.",
    basePrice: 45,
    priceUnit: "sqft" as const,
  },
  {
    name: "Plumbing Checkup",
    slug: "plumbing-checkup",
    category: "plumbing",
    icon: "Droplets",
    description: "Leak detection, pipe fitting and drainage fixes.",
    basePrice: 350,
    priceUnit: "session" as const,
  },
  {
    name: "AC Servicing Package",
    slug: "ac-servicing",
    category: "ac_repair",
    icon: "Wind",
    description: "Full AC cleaning, gas check and performance servicing.",
    basePrice: 1500,
    priceUnit: "session" as const,
  },
  {
    name: "Pest Control Treatment",
    slug: "pest-control",
    category: "pest_control",
    icon: "Bug",
    description: "Safe, effective treatment for common household pests.",
    basePrice: 1800,
    priceUnit: "session" as const,
  },
  {
    name: "Appliance Repair",
    slug: "appliance-repair",
    category: "appliance",
    icon: "Plug",
    description: "Diagnosis and repair for major home appliances.",
    basePrice: 600,
    priceUnit: "session" as const,
  },
];

const PROVIDERS = [
  {
    fullName: "Maya Shrestha",
    headline: "Home Cleaning · Kathmandu",
    bio: "Dedicated cleaning professional with 8 years of experience in luxury residential maintenance across Kathmandu Valley. Specialized in deep sterilization and eco-friendly organic cleaning solutions for modern homes. Known for discretion and meticulous standards.",
    categories: ["cleaning"],
    avatarSeed: "maya-shrestha",
    rating: 4.9,
    reviewCount: 847,
    hourlyRate: null,
    sessionPrice: 1200,
    area: "Kathmandu",
    distanceKm: 0.9,
    idVerified: true,
    bgChecked: true,
    licensed: true,
    insured: true,
    availableNow: true,
    topRated: true,
    experienceYears: 8,
    highlights:
      "Customers consistently praise Maya for her exceptional attention to detail and punctuality. She is frequently described as thorough and trustworthy, with multiple long-term clients noting her consistent quality over years of service.",
  },
  {
    fullName: "Rajesh K. Hamal",
    headline: "Home Cleaning · Kathmandu",
    bio: "Top-rated cleaning specialist known for fast turnaround without cutting corners. Runs a small trusted team for larger homes.",
    categories: ["cleaning"],
    avatarSeed: "rajesh-hamal",
    rating: 4.9,
    reviewCount: 128,
    hourlyRate: 850,
    sessionPrice: null,
    area: "Kathmandu",
    distanceKm: 0.8,
    idVerified: true,
    bgChecked: true,
    licensed: true,
    insured: false,
    availableNow: true,
    topRated: true,
    experienceYears: 6,
    highlights:
      "Rajesh is booked out weeks in advance for a reason — clients highlight his speed and the spotless finish he leaves every time.",
  },
  {
    fullName: "Anita Shrestha",
    headline: "Home Cleaning · Kathmandu",
    bio: "Reliable and friendly cleaner specializing in apartments and small homes.",
    categories: ["cleaning"],
    avatarSeed: "anita-shrestha",
    rating: 4.7,
    reviewCount: 94,
    hourlyRate: 700,
    sessionPrice: null,
    area: "Kathmandu",
    distanceKm: 1.5,
    idVerified: true,
    bgChecked: true,
    licensed: false,
    insured: false,
    availableNow: false,
    topRated: false,
    experienceYears: 3,
    highlights: "Anita is praised for being warm, communicative, and consistently on time.",
  },
  {
    fullName: "Prakash Thapa",
    headline: "Home Cleaning · Kathmandu",
    bio: "Detail-oriented cleaning professional with a perfect track record on Karya.",
    categories: ["cleaning"],
    avatarSeed: "prakash-thapa",
    rating: 5.0,
    reviewCount: 42,
    hourlyRate: 950,
    sessionPrice: null,
    area: "Kathmandu",
    distanceKm: 2.2,
    idVerified: true,
    bgChecked: true,
    licensed: true,
    insured: true,
    availableNow: true,
    topRated: true,
    experienceYears: 5,
    highlights: "Every review of Prakash mentions the same thing: flawless, careful work.",
  },
  {
    fullName: "Bijay Shrestha",
    headline: "Home Cleaning · Kathmandu",
    bio: "Fast, friendly, and available on short notice for same-day bookings.",
    categories: ["cleaning"],
    avatarSeed: "bijay-shrestha",
    rating: 4.9,
    reviewCount: 210,
    hourlyRate: 500,
    sessionPrice: null,
    area: "Kathmandu",
    distanceKm: 1.2,
    idVerified: true,
    bgChecked: true,
    licensed: false,
    insured: false,
    availableNow: true,
    topRated: false,
    experienceYears: 4,
    highlights: "Bijay's clients love how quickly he responds and shows up.",
  },
  {
    fullName: "Sunita Tamang",
    headline: "Home Cleaning · Kathmandu",
    bio: "Experienced housekeeper offering thorough, dependable cleaning.",
    categories: ["cleaning"],
    avatarSeed: "sunita-tamang",
    rating: 4.8,
    reviewCount: 156,
    hourlyRate: 600,
    sessionPrice: null,
    area: "Kathmandu",
    distanceKm: 2.5,
    idVerified: true,
    bgChecked: true,
    licensed: false,
    insured: false,
    availableNow: true,
    topRated: false,
    experienceYears: 5,
    highlights: "Sunita is known for going the extra mile on kitchens and bathrooms.",
  },
  {
    fullName: "Madan K.C.",
    headline: "Electrical · Kathmandu",
    bio: "Licensed electrician handling everything from fan repairs to full rewiring.",
    categories: ["electrical", "appliance"],
    avatarSeed: "madan-kc",
    rating: 4.8,
    reviewCount: 133,
    hourlyRate: 450,
    sessionPrice: null,
    area: "Kathmandu",
    distanceKm: 1.8,
    idVerified: true,
    bgChecked: true,
    licensed: true,
    insured: true,
    availableNow: true,
    topRated: true,
    experienceYears: 7,
    highlights: "Madan diagnoses problems fast and explains everything clearly before starting.",
  },
  {
    fullName: "Shiva Technical Hub",
    headline: "AC & Appliance Repair · Kathmandu",
    bio: "A trusted local team specializing in AC servicing and appliance repair.",
    categories: ["ac_repair", "appliance"],
    avatarSeed: "shiva-technical",
    rating: 4.7,
    reviewCount: 88,
    hourlyRate: null,
    sessionPrice: 1500,
    area: "Kathmandu",
    distanceKm: 3.1,
    idVerified: true,
    bgChecked: true,
    licensed: true,
    insured: true,
    availableNow: false,
    topRated: false,
    experienceYears: 6,
    highlights: "Clients trust Shiva Technical Hub for honest diagnostics and fair pricing.",
  },
  {
    fullName: "Prakash Gurung",
    headline: "Gardening · Kathmandu",
    bio: "Landscaping and lawn care specialist for residential gardens.",
    categories: ["gardening"],
    avatarSeed: "prakash-gurung",
    rating: 4.6,
    reviewCount: 61,
    hourlyRate: null,
    sessionPrice: 800,
    area: "Kathmandu",
    distanceKm: 2.0,
    idVerified: true,
    bgChecked: false,
    licensed: false,
    insured: false,
    availableNow: true,
    topRated: false,
    experienceYears: 4,
    highlights: "Prakash keeps gardens looking sharp with a reliable weekly routine.",
  },
  {
    fullName: "Green Hands Nursery",
    headline: "Gardening & Landscaping · Kathmandu",
    bio: "Full-service landscaping team offering garden design and upkeep.",
    categories: ["gardening"],
    avatarSeed: "green-hands",
    rating: 4.8,
    reviewCount: 74,
    hourlyRate: null,
    sessionPrice: 950,
    area: "Kathmandu",
    distanceKm: 2.8,
    idVerified: true,
    bgChecked: true,
    licensed: false,
    insured: false,
    availableNow: false,
    topRated: true,
    experienceYears: 9,
    highlights: "Green Hands is praised for creative landscaping ideas and tidy execution.",
  },
  {
    fullName: "Ramesh K.C.",
    headline: "Painting · Kathmandu",
    bio: "Professional painter for interior and exterior walls, neat and on schedule.",
    categories: ["painting"],
    avatarSeed: "ramesh-kc",
    rating: 5.0,
    reviewCount: 39,
    hourlyRate: 750,
    sessionPrice: null,
    area: "Kathmandu",
    distanceKm: 0.8,
    idVerified: true,
    bgChecked: true,
    licensed: false,
    insured: false,
    availableNow: true,
    topRated: true,
    experienceYears: 5,
    highlights: "Ramesh's line work and finish quality are consistently called out by clients.",
  },
  {
    fullName: "Urban Hands Kathmandu",
    headline: "Plumbing · Kathmandu",
    bio: "A professional plumbing outfit serving Kathmandu and Lalitpur.",
    categories: ["plumbing"],
    avatarSeed: "urban-hands",
    rating: 4.7,
    reviewCount: 102,
    hourlyRate: null,
    sessionPrice: 350,
    area: "Kathmandu",
    distanceKm: 1.4,
    idVerified: true,
    bgChecked: true,
    licensed: true,
    insured: true,
    availableNow: true,
    topRated: false,
    experienceYears: 6,
    highlights: "Urban Hands is known for arriving prepared and fixing it right the first time.",
  },
  {
    fullName: "Anish Karkee",
    headline: "Carpentry · Kathmandu",
    bio: "Skilled carpenter for furniture assembly, repairs and custom builds.",
    categories: ["carpentry"],
    avatarSeed: "anish-karkee",
    rating: 4.9,
    reviewCount: 67,
    hourlyRate: 500,
    sessionPrice: null,
    area: "Kathmandu",
    distanceKm: 1.1,
    idVerified: true,
    bgChecked: true,
    licensed: false,
    insured: false,
    availableNow: true,
    topRated: true,
    experienceYears: 7,
    highlights: "Anish is a top-rated pro known for precise, sturdy work.",
  },
  {
    fullName: "Sabin Rai",
    headline: "Pest Control · Kathmandu",
    bio: "Certified pest control technician using safe, family-friendly treatments.",
    categories: ["pest_control"],
    avatarSeed: "sabin-rai",
    rating: 4.6,
    reviewCount: 45,
    hourlyRate: null,
    sessionPrice: 1800,
    area: "Kathmandu",
    distanceKm: 3.4,
    idVerified: true,
    bgChecked: true,
    licensed: true,
    insured: false,
    availableNow: false,
    topRated: false,
    experienceYears: 4,
    highlights: "Sabin's treatments are noted for being effective without a lingering smell.",
  },
];

export async function seedCatalog() {
  const existingServices = await Service.count();
  if (existingServices === 0) {
    await Service.bulkCreate(SERVICES);
    console.log(`[Seed] Created ${SERVICES.length} services`);
  }

  const existingProviders = await Provider.count();
  if (existingProviders === 0) {
    const hashedPassword = await hashPassword(SEED_PROVIDER_PASSWORD);

    for (const providerData of PROVIDERS) {
      const user = await User.create({
        fullName: providerData.fullName,
        email: slugifyEmail(providerData.fullName),
        phoneNumber: null,
        password: hashedPassword,
        role: "provider",
        isVerified: true,
      });

      await Provider.create({
        ...providerData,
        userId: user.id,
        status: "approved",
      });
    }

    console.log(`[Seed] Created ${PROVIDERS.length} providers`);
    console.log(
      `[Seed] Demo provider accounts are loginable with password: ${SEED_PROVIDER_PASSWORD}`,
    );
    return;
  }

  // Providers already exist from an earlier version of this seed script,
  // before Provider rows were linked to a User account — backfill them
  // instead of skipping, so existing dev data keeps working.
  const orphaned = await Provider.findAll({ where: { userId: null } });
  if (orphaned.length > 0) {
    const hashedPassword = await hashPassword(SEED_PROVIDER_PASSWORD);

    for (const provider of orphaned) {
      const user = await User.create({
        fullName: provider.fullName,
        email: slugifyEmail(provider.fullName),
        phoneNumber: null,
        password: hashedPassword,
        role: "provider",
        isVerified: true,
      });
      await provider.update({ userId: user.id, status: "approved" });
    }

    console.log(`[Seed] Backfilled ${orphaned.length} legacy provider accounts`);
    console.log(
      `[Seed] Demo provider accounts are loginable with password: ${SEED_PROVIDER_PASSWORD}`,
    );
  }
}
